### ISSUE TITLE
ratelimit issue and also SECRET_KEY issue 

### ISSUE THREAD

**Issue by nepal4972** [nightmaregaurav/PPts#9] opened 2024-02-11 19:47 UTC
ImportError: cannot import name 'ratelimit' from 'ratelimit.decorators'

**Comment by nightmaregaurav** [comment] 2024-02-12 03:02
Please follow the readme.
SECRET_KEY issue is there because you did not set `DJANGO_ENV` environment variable. And `ratelimit.decorators` is probably there because you did not install all the dependencies.

Otherwise, please state:
  - What you did (Steps)
  - What was expected
  - What you got (The exact output)

I am closing this issue as I am unable to reproduce it, please reopen if you face the issue after following all the steps in the `readme.md` file.

**Closed by nightmaregaurav** 2024-02-12 03:02 UTC
